species_list:
  - scientific_name: "Pycnonotus cafer"
    common_name: "Red-vented Bulbul"
  - scientific_name: "Pycnonotus jocosus"
    common_name: "Red-whiskered Bulbul"
  - scientific_name: "Athene brama"
    common_name: "Spotted Owlet"
  - scientific_name: "Corvus splendens"
    common_name: "House Crow"
  - scientific_name: "Dicrurus macrocercus"
    common_name: "Black Drongo"

RAW_DIR: "../data/raw"
PROCESSED_DIR: "../data/processed"
SPECTROGRAM_DIR: "../data/spectrograms"
SPLIT_DIR: '../data/splited'
MODEL_PATH: "../models/checkpoints/best_model.pth"
CONFUSION_MATRIX_PATH: '../outputs/confusion_matrix.png'