species_list:
  - scientific_name: "Eudynamys scolopaceus"
    common_name: "Asian Koel"
  - scientific_name: "Copsychus saularis"
    common_name: "Oriental Magpie Robin"
  - scientific_name: "Pycnonotus cafer"
    common_name: "Red-vented Bulbul"
  - scientific_name: "Acridotheres tristis"
    common_name: "Common Myna"
  - scientific_name: "Pavo cristatus"
    common_name: "Indian Peafowl"
  - scientific_name: "Psittacula krameri"
    common_name: "Rose-ringed Parakeet"
  - scientific_name: "Athene brama"
    common_name: "Spotted Owlet"
  - scientific_name: "Halcyon smyrnensis"
    common_name: "White-throated Kingfisher"
  - scientific_name: "Hierococcyx varius"
    common_name: "Common Hawk-Cuckoo"
  - scientific_name: "Pycnonotus jocosus"
    common_name: "Red-whiskered Bulbul"

labels:
  - label: "song"
    int: 0
  - label: "call"
    int: 1
  - label: "call, song"
    int: 2
  - label: "call, nocturnal call"
    int: 3